### ISSUE TITLE
Typing: Narrow down types of arguments (NDFrame)

### ISSUE THREAD

**Issue by phofl** [noatamir/pyladies-workshop#10]
We prefer using ``Literal["a"] | Literal["b"]`` instead of ``str``. Look into the documentation what is allowed and the narrow the types down appropriately. Generally, we probably already have type definitions in ``pandas/_typing.py`` like ``NaPosition`` for the first item in the list below.

You can locate the appropriate file through searching for ``class NDFrame`` in the repository (This is the base class for Series and DataFrame).

**NDFrame methods:**

- [x] Specify ``closed`` in ``rolling`` more precisely
- [x] Specify ``method`` in ``expanding`` more precisely
- [x] Specify ``method`` in ``ewm`` more precisely
- [x] Specify ``engine`` in ``to_excel`` more precisely
- [x] Specify ``orient`` in ``to_json`` more precisely
- [x] Specify ``date_unit`` in ``to_json `` more precisely
- [x] Specify ``errors`` in ``to_hdf `` more precisely
- [x] Specify ``mode`` in ``to_hdf `` more precisely
- [x] Specify ``complib`` in ``to_hdf `` more precisely
- [x] Specify ``format`` in ``to_hdf `` more precisely
- [x] Specify ``method`` in ``to_sql `` more precisely
- [x] Specify ``errors`` in ``to_csv `` more precisely
- [x] Specify ``mode`` in ``to_csv `` more precisely
- [x] Specify ``kind`` and ``na_position`` in ``sort_values `` more precisely
- [x] Specify ``method`` in ``reindex `` more precisely
- [x] Specify ``method`` in ``interpolate `` more precisely
- [x] Specify ``limit_direction`` in ``interpolate `` more precisely
- [x] Specify ``limit_area`` in ``interpolate `` more precisely
- [x] Specify ``how`` in ``asfreq `` more precisely
- [x] Specify ``closed`` in ``resample `` more precisely
- [x] Specify ``convention`` in ``resample `` more precisely
- [x] Specify ``kind`` in ``resample `` more precisely
- [x] Specify ``method`` in ``rank `` more precisely
- [x] Specify ``na_option`` in ``rank `` more precisely

**Comment by YYYasin19** [comment]
I'll take these :)

**Comment by mKlepsch** [comment]
I'll take the 6 to 10 : 
 Specify date_unit in to_json  more precisely
 Specify errors in to_hdf  more precisely
 Specify mode in to_hdf  more precisely
 Specify complib in to_hdf  more precisely
 Specify format in to_hdf   more precisely

**Comment by kjanker** [comment]
Okay, I'll go with 11-15:
- [ ] Specify method in to_sql  more precisely
- [ ]  Specify errors in to_csv  more precisely
- [ ]  Specify mode in to_csv  more precisely
- [ ]  Specify kind and na_position in sort_values  more precisely
- [ ]  Specify method in reindex  more precisely

**Comment by VanMyHu** [comment]
I'll go with 16-18:
Specify method in interpolate more precisely
Specify limit_direction in interpolate more precisely
Specify limit_area in interpolate more precisely

**Comment by kevx82** [comment]
I'll take 18 to 19.

**Comment by kjanker** [comment]
@phofl @noatamir
