### ISSUE TITLE
Typing: Narrow down types of arguments (Index)

### ISSUE THREAD

**Issue by phofl** [noatamir/pyladies-workshop#11]
We prefer using Literal["a", "b"] instead of str. Look into the documentation what is allowed and the narrow the types down appropriately. Generally, we probably already have type definitions in pandas/_typing.py like NaPosition for the first item in the list below.

You can locate the appropriate file through searching for ``class Index`` in the repository.

**Index methods**

- [x] Specify ``method`` in ``get_indexer `` more precisely
- [x] Specify ``how`` in ``join `` more precisely
- [x] Specify ``na_position`` in ``sort_values `` more precisely
- [x] Specify ``method`` in ``reindex `` more precisely
- [x] Specify ``na_action`` in ``map `` more precisely

**Comment by kklein** [comment]
I'll take on
`Specify method in get_indexer  more precisely`
and 
`Specify method in reindex  more precisely`

**Comment by emptymalei** [comment]
Then I'll work on the rest if it is okay.
