### ISSUE TITLE
Add deprecation notes to pandas methods

### ISSUE THREAD

**Issue by phofl** [noatamir/pyladies-workshop#3]
We have a couple of methods that we want to deprecate right now:

- [x] https://github.com/pandas-dev/pandas/issues/52511
- [x] https://github.com/pandas-dev/pandas/issues/20251
- [x] Deprecate Index.ravel

You can follow the work that was done in this PR: https://github.com/pandas-dev/pandas/pull/51960

**Comment by JustinReboullot** [comment]
take

**Comment by noatamir** [comment]
@JustinReboullot @marechaux which of these are you doing? It would be helpful to know, so others can work on other methods ;)

**Comment by marechaux** [comment]
@JustinReboullot is doing the other currently
