### ISSUE TITLE
Add Copy-on-Write tests

### ISSUE THREAD

**Issue by phofl** [noatamir/pyladies-workshop#4]
We added many optimisations for 2.0 when Copy-on-Write is turned on.  Some of these are still missing tests because the optimization was implemented implicitly in other methods.

- [ ] DataFrame.join (more or less equivalent to the merge tests in pandas/tests/copy_view/test_functions.py)
- [ ] Add test for tz_convert where input timezone is timezone we convert to, e.g. a no-op
- [ ] Add test for tz_localize where operation is a no-op

**Comment by SecretLake** [comment]
I'd like to work on it :)
