### ISSUE TITLE
Add regression tests

### ISSUE THREAD

**Issue by phofl** [noatamir/pyladies-workshop#7]
Search for a minimal example and the confirmation that it's fixed. Add the test then

- [x] https://github.com/pandas-dev/pandas/issues/24205
- [x] https://github.com/pandas-dev/pandas/issues/32218
- [ ] https://github.com/pandas-dev/pandas/issues/33331
- [ ] https://github.com/pandas-dev/pandas/issues/34164
- [ ] https://github.com/pandas-dev/pandas/issues/37480
- [x] https://github.com/pandas-dev/pandas/issues/35665
- [x] https://github.com/pandas-dev/pandas/issues/48238
- [x] https://github.com/pandas-dev/pandas/issues/48521
- [ ] https://github.com/pandas-dev/pandas/issues/44078
- [ ] https://github.com/pandas-dev/pandas/issues/43996
- [x] https://github.com/pandas-dev/pandas/issues/22077
- [x] https://github.com/pandas-dev/pandas/issues/21932
- [x] https://github.com/pandas-dev/pandas/issues/19993
- [x] https://github.com/pandas-dev/pandas/issues/5355
- [x] https://github.com/pandas-dev/pandas/issues/24196
- [x] https://github.com/pandas-dev/pandas/issues/38147
- [ ] https://github.com/pandas-dev/pandas/issues/51500
- [x] https://github.com/pandas-dev/pandas/issues/4895
- [x] https://github.com/pandas-dev/pandas/issues/9048
- [ ] https://github.com/pandas-dev/pandas/issues/25548
- [ ] https://github.com/pandas-dev/pandas/issues/25298
- [ ] https://github.com/pandas-dev/pandas/issues/33457
- [x] https://github.com/pandas-dev/pandas/issues/33828
- [x] https://github.com/pandas-dev/pandas/issues/31581
- [ ] https://github.com/pandas-dev/pandas/issues/29707
- [ ] https://github.com/pandas-dev/pandas/issues/28871

**Comment by vagechirkov** [comment]
Hey, I would like to work on this issue: https://github.com/pandas-dev/pandas/issues/48521

**Comment by MarvinGravert** [comment]
Hi, I trying myself on this issue: [pandas-dev/pandas#35665](https://github.com/pandas-dev/pandas/issues/35665 )

**Comment by Gramet** [comment]
Hi, I'll take https://github.com/pandas-dev/pandas/issues/32218

**Comment by ArnaudChanoine** [comment]
Hi, I'll kook into pandas-dev/pandas#28871

**Comment by PrimeF** [comment]
Hi, I'll look into https://github.com/pandas-dev/pandas/issues/5355

**Comment by ArnaudChanoine** [comment]
Looking into pandas-dev/pandas#33828

**Comment by corriebar** [comment]
Looking into https://github.com/pandas-dev/pandas/issues/31581

**Comment by vagechirkov** [comment]
I will take this one https://github.com/pandas-dev/pandas/issues/38147 🙃

**Comment by gab50000** [comment]
I'll look into #48238

**Comment by DrorBendet** [comment]
taking pandas-dev/pandas/issues/38147

**Comment by MarvinGravert** [comment]
Looking into [https://github.com/pandas-dev/pandas/issues/29707](https://github.com/pandas-dev/pandas/issues/29707)

**Comment by MirijaH** [comment]
Looking into: pivot_table produces inconsistent columns if applied to empty table #21932

**Comment by oluwatonio** [comment]
I'll look into https://github.com/pandas-dev/pandas/issues/44078
