### ISSUE TITLE
Typing: Narrow down types of arguments (DataFrame)

### ISSUE THREAD

**Issue by phofl** [noatamir/pyladies-workshop#8]
We prefer using ``Literal["a"] | Literal["b"]`` instead of ``str``. Look into the documentation what is allowed and the narrow the types down appropriately. Generally, we probably already have type definitions in ``pandas/_typing.py`` like ``NaPosition`` for the first item in the list below.

You can locate the appropriate file through searching for ``class DataFrame`` in the repository.

**DataFrame methods:**

- [x] Specify``kind`` and ``na_position`` more precisely in ``sort_values``  (can look at ``sort_index``, it is already done there)
- [x] Specify ``keep`` for ``nsmallest`` and ``nlargest`` more precisely
- [x] Specify ``join`` and ``errors`` in ``update`` more precisely
- [x] Specify ``na_action`` in ``applymap`` more precisely
- [x] Specify ``validate`` in ``merge`` and ``join`` more precisely
- [x] Specify ``how`` in ``to_timestamp`` more precisely
- [x] Specify ``orient`` in ``from_dict`` more precisely
- [x] Specify ``if_exists`` in ``to_gbq`` more precisely
- [x] Specify ``byteorder`` in ``to_stata`` more precisely
- [x] Specify ``engine`` in ``to_parquet`` more precisely
- [x] Specify ``engine`` in ``to_orc`` more precisely
- [x] Specify ``parser`` in ``to_xml`` more precisely
- [x] Specify ``method`` in ``reindex`` more precisely

**Comment by benedikt-mangold** [comment]
take

**Comment by benedikt-mangold** [comment]
- [x] Specifykind and na_position more precisely in sort_values (can look at sort_index, it is already done there)

**Comment by pschleiter** [comment]
[x] Specify method in reindex more precisely

**Comment by benedikt-mangold** [comment]
- [x]  Specify keep for nsmallest and nlargest more precisely

**Comment by benedikt-mangold** [comment]
- [x]  Specify join and errors in update more precisely

**Comment by benedikt-mangold** [comment]
-[x]  Specify na_action in applymap more precisely

**Comment by benedikt-mangold** [comment]
- [x] Specify validate in merge and join more precisely

**Comment by pschleiter** [comment]
- [x] Specify engine in to_orc more precisely
- [x] Specify parser in to_xml more precisely

**Comment by benedikt-mangold** [comment]
- [x]  Specify if_exists in to_gbq more precisely

**Comment by pschleiter** [comment]
- [x] Specify engine in to_parquet more precisely

**Comment by benedikt-mangold** [comment]
- [x]  Specify byteorder in to_stata more precisely

**Comment by benedikt-mangold** [comment]
should be done, we will merge our branches
